var pubKey = `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCfvWqJp7Fnx0Uo0rpw9xAULxMy
W0MaRcBX9CSTjEdUiwPU5dPtfcJM/D4SIcZF0vqXvAX9efmcrYEAasZWNAIDxrHI
tvfcoLXBdkRBaa6aF/SiOZVOkN2e3bsRZiyt8VNmtPT5ghVZPxAgZFkIn/JWE2CI
PgJZllxhGyk3ns0qvQIDAQAB
-----END PUBLIC KEY-----`